apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:beta-php8.3-fpm-alpine
        env:
          - name: WORDPRESS_DB_NAME 
            valueFrom:
              configMapKeyRef:
                name: wpconfig 
                key: WORDPRESS_DB_NAME
          - name: WORDPRESS_DB_HOST 
            valueFrom:
              configMapKeyRef:
                name: wpconfig 
                key: WORDPRESS_DB_HOST
          - name: WORDPRESS_DB_USER 
            valueFrom:
              secretKeyRef:
                name: wpsecret 
                key: WORDPRESS_DB_USER
          - name: WORDPRESS_DB_PASSWORD 
            valueFrom:
              secretKeyRef:
                name: wpsecret 
                key: WORDPRESS_DB_PASSWORD
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ingree
spec:
  rules:
  - host: "example.org"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: wordpress-service
            port:
              number: 80
  - host: "db.example.org"
    http:
      paths:
      - pathType: Prefix
        path: "/phpmyadmin"
        backend:
          service:
            name: pma-service
            port:
              number: 80

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wordpress-np
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: mysql
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          role: wordpress
    ports:
    - protocol: TCP
      port: 80
      port: 443