apiVersion: v1
kind: Secret
metadata:
  name: wpsecret
data:
  WORDPRESS_DB_USER: bGFzdF9hc3NpZ25tZW50Cg==
  WORDPRESS_DB_PASSWORD: bGFzdF9hc3NpZ25tZW50Cg==

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: wpconfig
data:
  WORDPRESS_DB_NAME: "last_assignment"
  WORDPRESS_DB_HOST: "mysql-service"