apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: last_assignment
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer


---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: last_assignment
  hostPath:
    path: "/home/arman/mysql/data"
