apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma
  labels:
    app: pma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pma
  template:
    metadata:
      labels:
        app: pma
    spec:
      containers:
      - name: pma
        image: phpmyadmin:latest
        env:
          - name: PMA_USER
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: PMA_USER

          - name: PMA_HOST
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: PMA_HOST

          - name: PMA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_ROOT_PASSWORD
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: pma-service
spec:
  selector:
    app: pma
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
